---
- name: pull and run jenkins image
  hosts: hosts
  remote_user: vagrant
  become: true

  tasks:
  - name: get and run nexus container
    docker_container:
      name: nexusContainer
      state: started
      image: sonatype/nexus
      ports:
        - "50000:8081"
